name: Workflow1
on: workflow_dispatch
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.0"
      - name: install dependencies
        run: npm install
      - name: run linter
        run: npm run lint
  testing:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.0"
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm run test
  building:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: download repo
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.0"
      - name: install dependencies
        run: npm install
      - name: make build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-output
          path: dist
